name: ci

on:
  push:
    branches:
      - codex
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  ci:
    name: ci
    runs-on: ubuntu-24.04
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: checkout-submodules
        run: |
          git -c protocol.version=2 submodule update --init --depth=1 --jobs=32

      - name: build
        run: |
          podman run \
            --entrypoint /workspace/ghc/.codex/build.sh \
            --network host \
            --rm \
            --tmpfs /tmp:exec \
            --volume $PWD:/workspace/ghc \
            --workdir /workspace/ghc \
            ghcr.io/openai/codex-universal

      - name: cleanup-before-test
        run: |
          git clean -xdf --exclude=codex-cache.tar.zst
          git submodule foreach git clean -xdf

      - name: test
        run: |
          podman run \
            --entrypoint /workspace/ghc/.codex/test.sh \
            --network host \
            --rm \
            --tmpfs /tmp:exec \
            --volume $PWD:/workspace/ghc \
            --workdir /workspace/ghc \
            ghcr.io/openai/codex-universal

      - name: upload-release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release delete --cleanup-tag --yes latest || true
          gh release create --latest latest codex-cache.tar.zst
          gh run list --status completed --json databaseId --jq '.[].databaseId' | xargs -r -n1 gh run delete
